### ISSUE TITLE
Failure to override some methods when UIView is the super class

### ISSUE THREAD

**Issue by jimgoog** [JetBrains/kotlin-native#1035]
Overriding most methods appears to work in KotlinNative, but for whatever reason, the layout methods on `UIView` appear to give a compile error when you try to override them. 
 Specifically, they give errors like `'layoutSubviews' overrides nothing`.

```
@ExportObjCClass
class MyView : UIView {
    constructor(frame: CValue<CGRect>) : super(frame);

    override fun layoutSubviews()  // Compile error here: 'layoutSubviews' overrides nothing
    {
        println("this function was called to layout subviews!!!")
    }
}
```
Checking the objc.kt file from an older version of KotlinNative suggests that maybe the problem is that layoutSubviews is defined in the interop as an extension method rather than a method on the base class?

How / What is the best practice for overriding this method on UIView?

**Comment by SvyatoslavScherbina** [comment]
> maybe the problem is that layoutSubviews is defined in the interop as an extension method rather than a method on the base class?

Yes, this seems to be the case.
`layoutSubviews` is declared as category method in Objective-C headers, and category methods are currently represented as Kotlin extension methods.

Extension methods can't be overridden in Kotlin. However, as a workaround, you can declare `layoutSubviews` Kotlin method without `override` keyword, and add `@ObjCAction` annotation to make it visible through Objective-C virtual dispatch:

```
class MyView : UIView {
   @ObjCAction fun layoutSubviews() {
        ...
    }
}
```

(Note that `@ObjCAction` is applicable to methods with very strict constraints on their signatures, namely methods that can be used as actions in target-action pattern. That's why adding `@ObjCAction` is just a workaround).

**Comment by olonho** [comment]
Is there anything left with this issue?
