### ISSUE TITLE
Missing documentation about `konanArtifacts.framework()`

### ISSUE THREAD

**Issue by StefMa** [JetBrains/kotlin-native#1211]
In the [calculator readme](https://github.com/JetBrains/kotlin-native/blob/2e07b3f52f99b51d353a8c0e53bdf9fff86988e0/samples/calculator/build.gradle#L24) we use in the `kotlinArtifcats` gradle extensions `framework()`.
I guess I know what it means and what it does. 
It build a iOS framework with the we passed in.

But it isn't well documented [here](https://github.com/JetBrains/kotlin-native/blob/master/GRADLE_PLUGIN.md).
It would be great if someone can add this who have deep knowledge what we can pass in into the framework() and what it really does...

**Comment by Albert-Gao** [comment]
Same question here, or at least a clue on how to build a framework with the command line:

I tried to re-build a framework using the following command:

`../../dist/bin/kotlinc -produce framework ./src/main/kotlin/org/konan/arithmeticparser/Parser.kt`

But it doesn't work..., the outcome has a different structure compared to the gradle build one.

Any suggestion here?

**Comment by mouse4d** [comment]
I would also add that it would've been fantastic if there was a sample doing the same with CMake in CLion!

Background: I'm an iOS developer looking for a possibility to reuse code for an iOS and Android  library (actually .framework and .jar). I have no experience with any of CMake, gradle, or kotlin, but from what I could wrap my head around - Kotlin Native looks really promising and far more attractive than a C++ lib.

**Comment by StefMa** [comment]
Hey @mouse4d 

you can take a look into the [calculator sample](https://github.com/JetBrains/kotlin-native/tree/master/samples/calculator). There is "everything included" how to build a jar and a framework side by side...
The jar can be easily published to any maven repo (for example) or directly within a android project.

I've also created a sample here which do exactly that.
Before the andorid app builds it generate the jar from the shared code and put it to the android dependencies.

**Comment by mouse4d** [comment]
Hi @StefMa 

thanks a lot for the hint, I did look into all examples and those are really helpful! 

But what I meant is that I tried creating a `.framework` from a CLion project (which of course is using CMake) having as a starting base the `HelloWorld` sample project (chosen when creating a new Kotlin Native project) and I got a little bit confused, because while there are the CMake functions for library and executable artefacts in the `KotlinCMakeModule` (`konanc_library` and `konanc_executable`) I couldn't find the `konanc_framework` function that would correspond to framework() used in` kotlinArtifcats` gradle extensions.**\***

I hope this made sense :D

So I added my background with the hope that it will motivate the people writing the docs to try to make them more "idiot proof", because there might be more developers like me that know nothing about any of the toolchains used but still want to give Kotlin Native a shot, and for them (me) the learning curve is not really a curve but almost a vertical! 🙃 

**\*** this, by the way, I solved by copying the `konanc_library` function and changing `.klib` to `.framework`  and `-produce library` to `-produce framework`. I don't know where I could contribute this though.

**Comment by Albert-Gao** [comment]
@mouse4d 
I have a blog post of creating Kotlin Native iOS project without `CLion`:

You can check it here:
http://www.albertgao.xyz/2018/01/14/how-to-create-kotlin-native-ios-project/

Two ways:
1. Implement all the iOS-side code in Kotlin
2. Generate KN code as an iOS framework and use it in a XCode project

Seems fine to me, just post here to see if it could help you.

**Comment by olonho** [comment]
https://github.com/JetBrains/kotlin-native/pull/1247

**Comment by ilmat192** [comment]
@mouse4d Yes, currently there is no support for frameworks in CMake (because our main target is still Gradle) but it's should be easy to add such a support. I think we'll do this.
The #1247 PR with some readme updates is merged so I think the issue may be closed.
