### ISSUE TITLE
Unit in Kotlin not converts to Void in Swift when generating iOS framework

### ISSUE THREAD

**Issue by Albert-Gao** [JetBrains/kotlin-native#1271]
I want to declare a function which returns nothing. 
So I declared an interface in Kotlin side which includes the following function signature:

```kotlin
var errorCallback: (errMessage: String) -> Unit
```
when generating iOS framework, it will be converted to:

```objective-c
NativeLibsStdlibUnit*(^errorCallback)(NSString*);

@interface NativeLibsStdlibUnit : KotlinBase
+ (instancetype)unit NS_SWIFT_NAME(init());
@end;
```

Shouldn't it be `Void` in Swift?
I expected its counterpart in swift to be:

```swift
var successCallback: (_ result: String) -> Void
```

Is it a bug or I did something wrong?

**Comment by SvyatoslavScherbina** [comment]
This behaviour is intentional and related to some details of Kotlin generics such as covariance and type erasure.
It doesn't seem to impose any limitations on usage, does it?

**Comment by SvyatoslavScherbina** [comment]
When `Unit` is used as a return type of function (not a function type), it is translated to Swift `Void` (and Objective-C `void`). E.g.
```
fun foo(): Unit
```
is translated to
```
-(void)foo;
```

So the behaviour described above applies only to function types (i.e. types of lambdas).

**Comment by Albert-Gao** [comment]
@SvyatoslavScherbina Hi, thanks for the answer! I just got a little bit confused:

`When Unit is used as a return type of function (not a function type), it is translated to Swift Void (and Objective-C void).`

So, how to declare a lambda which returns nothing in kotlin native, and what's the counterpart in swift looks like?

**Comment by SvyatoslavScherbina** [comment]
If you need to implement your `errorCallback` in Swift, then you can assign a Swift lambda to it, and return `NativeLibsStdlibUnit()` from the lambda.

**Comment by Albert-Gao** [comment]
Which means I indeed need to follow the generated ObjC code which has the following signature:

```swift
var successCallback: (_ result: String) -> NativeLibsStdlibUnit()
```

A little bit weird but thanks!

**Comment by acecilia** [comment]
Hi :)
I just had the same issue. The following Kotlin function:
```
fun benchmark(callback: (String) -> Unit)
```

In Swift looks like:
```
func benchmark(callback: @escaping (String) -> KotlinUnit)
```

When the right thing would be:
```
func benchmark(callback: @escaping (String) -> Void)
```

Shouldn't this issue stay open?
Thanks!

**Comment by JakeWharton** [comment]
Same behavior as Java. Seems like it's working as intended.

**Comment by acecilia** [comment]
@JakeWharton For swift, the proper behavior would be to substitute `Unit` for `Void`, as it is happening with functions and explained in https://kotlinlang.org/docs/reference/native/objc_interop.html

**Comment by JakeWharton** [comment]
The same is true for Java and yet as already stated there are reasons why that is not the case.

**Comment by acecilia** [comment]
Then seems to me that in both platforms the right thing to do is to substitute `Unit` for `Void`. As I understand, this is not happening due to implementation details related with "Kotlin generics such as covariance and type erasure". 

That is why I am wondering if the issue should be reopened, so could be that a developer wants to look into it and fix it.

**Comment by SvyatoslavScherbina** [comment]
`() -> Unit` is subtype of `() -> Any` in Kotlin, so Swift counterparts should follow the same rule.
And `() -> KotlinUnit` is subtype of `() -> AnyObject` in Swift, while `() -> Void` is not.

This consideration is one of the reasons for mapping `() -> Unit` to `() -> KotlinUnit`.

**Comment by acecilia** [comment]
And why is `Unit` converted to `Void` in functions then? (According to https://kotlinlang.org/docs/reference/native/objc_interop.html)

**Comment by SvyatoslavScherbina** [comment]
Because this case is much more important, and consequences of translating `Unit` to `Void` are not that serious here.
Tradeoffs are everywhere.

**Comment by SvyatoslavScherbina** [comment]
Improved with #2968. Will likely be shipped within 1.3.40.

**Comment by arkivanov** [comment]
I'm wondering if this could be further improved for cases with functions as function arguments:
```kotlin
val foo = (callback: () -> Unit) -> Unit
```

The `callback` argument is still mapped to `() -> KotlinUnit`.

My use case: I'm working on a Swift framework for interop with Reaktive library, and bumped into this limitation. The library [KMP-NativeCoroutines](https://github.com/rickclephas/KMP-NativeCoroutines) by @rickclephas is [affected](https://github.com/rickclephas/KMP-NativeCoroutines/blob/master/KMPNativeCoroutinesCore/NativeCallback.swift) as well. Such a Swift framework can't depend on a Kotlin library for which the interop is being provided. This is because when the Swift framework will be used in a project, the Kotlin types won't be compatible, even though they are "same". Now, if I want to write a Swift interop function for Kotlin's type `(callback: () -> Unit) -> Unit`, I am forced to use additional generic types.

Either:
```swift
public typealias KotlinFoo<Unit> = (() -> Unit) -> Void

public func interop<Unit>(foo: KotlinFoo<Unit>, unit: Unit) {
    foo {
        // do something
        return unit
    }
}
```

or
```swift
public typealias KotlinFoo<Unit> = ((Unit) -> Unit) -> Void

public func interop<Unit>(foo: KotlinFoo<Unit>) {
    foo { (unit) in
        // do something
        return unit
    }
}
```

Both APIs are bloated with the `Unit` generic type and the `Unit` argument.

**Comment by SvyatoslavScherbina** [comment]
@arkivanov this issue is closed.
Please create a new one at https://kotl.in/issue

**Comment by arkivanov** [comment]
Thanks. For reference, filed [KT-47997](https://youtrack.jetbrains.com/issue/KT-47997).
