### ISSUE TITLE
Getting Double results from kotlin.math in wasm

### ISSUE THREAD

**Issue by boyanio** [JetBrains/kotlin-native#1394]
Hello. I am playing around with `kotlin.math` in wasm. I have the following functions:

```
@Used
public fun f1(): Double {
  var a: Double = round(56.3)
  return a
}

@Used
public fun f2(): Double {
  var a: Double = 56.3
  return a
}
```

When calling `f2` in JavaScript (`instance.exports["'kfun:f1$$ValueType'"]()`), it works fine. But when calling `f1`, I get 0. I see the generated code for `kotlin.math` uses *upper & lower* representation of a double. Is there anything specific around getting a Double result then?

**Comment by olonho** [comment]
Double Kotlin type is passed between WASM and JS worlds as two integer, and returned using global `ReturnSlot_setDouble`, see https://github.com/JetBrains/kotlin-native/blob/master/runtime/src/main/cpp/ReturnSlot.cpp. Generally, mode of operations where Kotlin is called from JS is not yet fully functional, so it may not work the way you expect.

**Comment by olonho** [comment]
Closing, please reopen if still relevant.

**Comment by WolfieWerewolf** [comment]
@olonho I found this ticket because I am attempting to do something similar to the OP except in my case I don't need to call WASM exported functions from JS; I'm looking at how I might be able to help you guys to move the JS Interop forward... so a simple test.  If I hijack your "poor man's IDL" for dom.kt like this

```javascript
package org.jetbrains.kotlin.native.interop.gen.wasm.idl

// This shall be an output of Web IDL parser.
val idlDom = listOf(
//    Interface("CanvasRenderingContext2D",
//        Attribute("lineWidth", idlInt),
//        Attribute("fillStyle", idlString),
//        Attribute("strokeStyle", idlString),
//
//        Operation("lineTo", idlVoid, Arg("x", idlInt), Arg("y", idlInt)),
//        Operation("moveTo", idlVoid, Arg("x", idlInt), Arg("y", idlInt)),
//        Operation("beginPath", idlVoid),
//        Operation("stroke", idlVoid),
//        Operation("fillRect", idlVoid, Arg("x", idlInt), Arg("y", idlInt), Arg("width", idlInt), Arg("height", idlInt)),
//        Operation("fillText", idlVoid, Arg("test", idlString), Arg("x", idlInt),  Arg("y", idlInt), Arg("maxWidth", idlInt)),
//        Operation("fill", idlVoid),
//        Operation("closePath", idlVoid)
//    ),
        Interface("WebGLRenderingContext",
                Attribute("width", idlInt),
                Attribute("height", idlInt),
                Attribute("COLOR_BUFFER_BIT", idlInt),
                Operation("clearColor", idlVoid, false, Arg("r", idlInt), Arg("g", idlInt), Arg("b", idlInt), Arg("a", idlInt)),

                //Operation("clearColor", idlVoid, false, Arg("r", idlInt), Arg("g", idlInt), Arg("b", idlInt), Arg("a", idlDouble)),
                //Operation("clearColor", idlVoid, false, Arg("r", idlDouble), Arg("g", idlDouble), Arg("b", idlDouble), Arg("a", idlDouble)),

                Operation("clear", idlVoid, Arg("mask", idlInt))
                ),
```
and then further hijack the html5canvas sample like this
```javascript
import kotlinx.interop.wasm.dom.*
import kotlinx.wasm.jsinterop.*

fun main(args: Array<String>) {
    val canvas = document.getElementById("myCanvas").asCanvas
    val gl = canvas.getContext("webgl")
    gl.clearColor(0, 1, 2, 1)
    gl.clear(gl.COLOR_BUFFER_BIT)
}
```
I am pleasantly surprised to get the following result:
![image](https://user-images.githubusercontent.com/10762757/37463455-ffed1d6e-2833-11e8-8d20-501519514c93.png)
It's the most basic of WebGL tests but it gives me some good information.  My first observation is that the StubGenerator will need to be re-factored to handle overloaded idl functions since "Canvas" "getContext" can have multiple modes of operation, I can think of three off the top of my head (canvas2D, WebGl and WebGl2)... but putting that aside for a minute the actual clearColor API accepts a double, not an int, but JS is flexible and interpreted the ints that I sent as doubles so it worked... however if I modify the above swapping in one of the commented lines:
```javascript
Operation("clearColor", idlVoid, false, Arg("r", idlInt), Arg("g", idlInt), Arg("b", idlInt), Arg("a", idlDouble)),
```
in this case I only changed the alpha to accept a double to keep it simple... the result is a white canvas and any attempt that I make to output the aUpper or aLower reveals that the value is 0 (completely transparent)... I've put console logs all over the place in the html5CanvasWasm.js wherever the value might show up and everywhere I see the same result, 0 everywhere.... So I don't think the the double is being converted to the int pair as expected somewhere along the pipeline.

I'd be more than happy to continue troubleshooting this but could use a little advice.  I looked at the ReturnSlot.cpp but I don't know how to get output from that cpp which is compiled to wasm and executed by the browser...
Any hints would be helpful.
Also, I am running on Debian 9 and using IntelliJ ultimate and just compiling using the build scripts provided which seems to work as I'm able to make changes and see results.
Kind Regards
/W

**Comment by WolfieWerewolf** [comment]
Oh I should mention.. when testing with the double alpha I simply changed:
```javascript
gl.clearColor(0, 1, 2, 1)
```
to
```javascript
gl.clearColor(0, 1, 2, 1.0)
```

**Comment by WolfieWerewolf** [comment]
and finally, this will be my last comment ;-) I just looked at:
```javascript
data class idlInterfaceRef(val name: String): Type
```
A possible solution to the overload could be to convert this to a Type[] or MutableList<Type> and then when iterating / parsing the array / List just add some random prefix to the generated name to handle the overload?  Is that a reasonable solution if I want to try to make some enhancements?

**Comment by WolfieWerewolf** [comment]
Hi @olonho I have an update on this..
I tracked the issue down to jsinterop.kt.  I don't know much about all that bit conversion you did and my solution certainly isn't as fancy as the original code but this is working:
```javascript
//const val upperWord = 0xffffffff.toLong() shl 32

@ExportForCppRuntime
fun doubleUpper(value: Double): Int {
    return value.toString().split(".")[0].toInt()
    //return ((value.toBits() and upperWord) ushr 32) .toInt()
}

@ExportForCppRuntime
fun doubleLower(value: Double): Int {
    return value.toString().split(".")[1].toInt()
    //return (value.toBits() and 0x00000000ffffffff) .toInt()
}
```
Then it's necessary to modify the html5Canvas.wasm.js (I presume this is generated from a template js file somewhere.. I haven't looked yet) but with the above change it's necessary to modify the following on the JS side.
```javascript
// function twoIntsToDouble(upper, lower) {
//     var buffer = new ArrayBuffer(8);
//     var ints = new Int32Array(buffer);
//     var doubles = new Float64Array(buffer);
//     ints[1] = upper;
//     ints[0] = lower;
//     return doubles[0];
// }
function twoIntsToDouble(upper, lower) {
    return +upper + lower
}
```
With those changes I am able to pass the double using the previously supplied idl code.
I look forward to hearing your thoughts on this... If this is an acceptable solution I would be happy to commit the changes to my fork and create a PR.   Like I said I don't know much about all that bit manipulation but I do know that where JS is concerned that level of precision is really not necessary...  I also feel the refactored twoIntsToDouble() that I provided is lighter than the previous version.
Kind Regards
/W

**Comment by WolfieWerewolf** [comment]
Ok I found the js template.. it seems to live in dist/klib/common/target/wasm32/included/launcher.js
I've gone ahead and pushed my changes to my fork here:
https://github.com/WolfieWerewolf/kotlin-native
Ideally I would like to discuss the design objectives for the IDL parser / generator to see if there's something I can do to help on that front.  You likely wouldn't want to merge this with the canvas demo broken so it would be necessary to handle the overloaded idl functions issue first.
Kind Regards
/W

**Comment by WolfieWerewolf** [comment]
Hi @olonho I've taken a few steps further and made the necessary changes to my fork to handle the overloading that I discussed above.  I was really hoping that the Kotlin Native compiler, or perhaps it's a limitation of LLVM in this case, would permit overloads to be identified by the return  type instead of just the arguments because if this worked I wouldn't have had to introduce a tiny bit of "hackery" to make this possible.  Perhaps we can call it a "feature request"  allow overloads to be identified by return type alone or in addition to arguments passed?

Effectively I modified the idl.kt to include an IArg interface like this:

```javascript
interface IArg{
    val name: String
    val type: Type
}
```
implemented the interface on Arg
```javascript
data class Arg(override val name: String, override val type: Type): IArg
```
and then introduced a "FakeArg" (this is the hackery) which also implements this interface
```javascript
data class FakeArg(override val name: String="", override val type: Type): IArg
```
Then I restored the dom.kt idl implementation to the original from your source and made the bare minimum changes to handle the use case for multiple contexts (of different types) as follows:
```javascript
Interface("CanvasRenderingContext2D",
                Attribute("lineWidth", idlInt),
                Attribute("fillStyle", idlString),
                Attribute("strokeStyle", idlString),

                Operation("lineTo", idlVoid, Arg("x", idlInt), Arg("y", idlInt)),
                Operation("moveTo", idlVoid, Arg("x", idlInt), Arg("y", idlInt)),
                Operation("beginPath", idlVoid),
                Operation("stroke", idlVoid),
                Operation("fillRect", idlVoid, Arg("x", idlInt), Arg("y", idlInt), Arg("width", idlInt), Arg("height", idlInt)),
                Operation("fillText", idlVoid, Arg("test", idlString), Arg("x", idlInt),  Arg("y", idlInt), Arg("maxWidth", idlInt)),
                Operation("fill", idlVoid),
                Operation("closePath", idlVoid)
        ),
        Interface("WebGLRenderingContext",
                Attribute("COLOR_BUFFER_BIT", idlInt),
                Operation("clearColor", idlVoid, false, Arg("r", idlDouble), Arg("g", idlDouble), Arg("b", idlDouble), Arg("a", idlDouble)),
                Operation("clear", idlVoid, Arg("mask", idlInt))
        ),
```
```javascript
Interface("Canvas",
                Operation("getContext", idlInterfaceRef("CanvasRenderingContext2D"), Arg("context", idlString)),
                Operation("getContext", idlInterfaceRef("WebGLRenderingContext"), Arg("context", idlString), FakeArg("fake", idlString)),
                Operation("getBoundingClientRect", idlInterfaceRef("DOMRect"))
        ),
```
everything else is unchanged

Then to make use of this I had to make a number of changes in the StubGenerator.. I won't go into full detail here, you can look at the diff between my branch and master but the resulting generated kotlin in kotlin_stubs looks a bit like this.
```javascript
@SymbolName("knjs__Canvas_getContext_CanvasRenderingContext2D")
external public fun knjs__Canvas_getContext_CanvasRenderingContext2D(arena: Int, index: Int, contextPtr: Int, contextLen: Int, resultArena: Int): Int

@SymbolName("knjs__Canvas_getContext_WebGLRenderingContext")
external public fun knjs__Canvas_getContext_WebGLRenderingContext(arena: Int, index: Int, contextPtr: Int, contextLen: Int, fakePtr: Int, fakeLen: Int, resultArena: Int): Int
```
the javascript is also modified to make use of the additional naming...
So I went ahead and restored the original html5Canvas example and created a new sample, webgl, which still only performs the original minimal test with the clearColor.  I'll start expanding it with more WebGLContext API to try to discover what else might break / what other cases need to be handled by the IDL parser / generator.  I expect that it would make the most sense to implement a lot of  this stuff by hand, as you have done, initially to discover the various cases, and then implement the idl parser.
A couple of things to note.  I've expanded a number of the functions to use a block body because it's easier to debug, and also used a stringbuilder in places also because it's easier to debug but I appreciate that SB is not ideal for code generation so this type of thing can be re-factored to be leaner later.. for now though I want to be able to output various substrings from the generated code to review in isolation etc.
With my fork it's now possible to use the webGl demo from the same kotlin-native source as the html5demo just like this:
```javascript
fun main(args: Array<String>) {
    val canvas = document.getElementById("glCanvas").asCanvas
    val gl = canvas.getContext("webgl").asWebGLRenderingContext
    doClear(gl)
}

fun doClear(gl: WebGLRenderingContext){
    gl.clearColor(0.0, 1.0, 2.0, 1.0)
    gl.clear(gl.COLOR_BUFFER_BIT)
}
```
Kind Regards
/W

**Comment by WolfieWerewolf** [comment]
Further looking at the kronos.org WebGL specification I am reminded that the signature for a WebGL context is actually different already, making my "FakeArg" actually unnecessary in this case.
https://www.khronos.org/registry/webgl/specs/latest/1.0/#5.3
```javascript
Here is an ECMAScript example which passes a WebGLContextAttributes argument to getContext. It assumes the presence of a canvas element named "canvas1" on the page.
var canvas = document.getElementById('canvas1');
var context = canvas.getContext('webgl',
                                { antialias: false,
                                  stencil: true });
```
So I will re-factor to include the WebGLContextAttributes argument...
