### ISSUE TITLE
iOS linker failure with 0.7 (ld: framework not found Greeting)

### ISSUE THREAD

**Issue by thevery** [JetBrains/kotlin-native#1583]
Sample here: https://github.com/thevery/kotlin-native-mpp (based on #1494)
```
ld: framework not found Greeting
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

But when I change `classpath "org.jetbrains.kotlin:kotlin-native-gradle-plugin:0.7"` to `classpath "org.jetbrains.kotlin:kotlin-native-gradle-plugin:0.7-dev-1407"` in `greeting/build.gradle` build fixes and works ok even after plugin version revert (looks like result is cached somewhere - gradle/git clean doesn't break the build).

**Comment by ilmat192** [comment]
The mechanism of passing IDE options (such as output directory, debug symbols etc) has been changed in `0.7`. In `0.6.2` these options were passed via environment variables while `0.7` uses project properties for it due to https://github.com/gradle/gradle/issues/3468. 

This sample was written for `0.6.2` and runs the Gradle build as if it uses environment variables. So the problem you reported may be fixed just by replacing a script building the framework in XCode with the following one:

```
"$SRCROOT/../gradlew" -p "$SRCROOT/../greeting/ios" "$KONAN_TASK" \
-Pkonan.configuration.build.dir="$CONFIGURATION_BUILD_DIR"        \
-Pkonan.debugging.symbols="$DEBUGGING_SYMBOLS"                    \
-Pkonan.optimizations.enable="$KONAN_ENABLE_OPTIMIZATIONS"
```

Here the project properties are used instead of environment variables. This change is already mentioned in the readme file so we only need to update the PR with this sample.

**Comment by ilmat192** [comment]
Looks like we can close this issue. @thevery do you have any objections?

**Comment by thevery** [comment]
Works for me, thanks!
