### ISSUE TITLE
EXC_BAD_ACCESS on async calls to iOS platform

### ISSUE THREAD

**Issue by kengura** [JetBrains/kotlin-native#1596]
I'm trying to implement Android/iOS project with shared common module written with Kotlin/Native. I have an issue with asynchronous calls from common module to iOS.

For example there is some async api defined in common module
```
interface ApiCallback {
    fun result()
}

expect class AsyncApi {
    fun asyncCall(callback: ApiCallback)
}
```

Actual implementation in iOS platform module
```
import platform.darwin.*

actual open class AsyncApi {

    actual fun asyncCall(callback: ApiCallback) {
        dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT.toLong(), 0)) {
            println("before callback invocation")
            callback.result()
            println("after callback invocation")
        }
    }
}
```

After calling it from common module 
```
private fun makeAsyncCall() {
    api.asyncCall(object : ApiCallback {
        override fun result() {
            println("ApiCallback result")
        }
    })
}
```
i can see result in debugging console:
```
before callback invocation
ApiCallback result
after callback invocation
```
But immediately after this there is EXC_BAD_ACCESS exception
```
#0	0x0000000108333bda in FreeContainer(ContainerHeader*) ()
#1	0x000070000ea3aca0 in 0x70000ea3aca0 ()
#2	0x00000001083333b7 in ReleaseRef(ObjHeader const*) ()
#3	0x000000010833ecdd in LeaveFrame ()
#4	0x00000001083445dd in platform_darwin_kniBridge206 ()
#5	0x0000000108344889 in __platform_darwin_kniBridge205_block_invoke ()
#6	0x000000010a4522f7 in _dispatch_call_block_and_release ()
#7	0x000000010a45333d in _dispatch_client_callout ()
...
``` 

I'm getting the same behavior for v0.6.2 and v7.0
You could check the project here: https://github.com/kengura/kotlin_multiplatform/tree/master
Am i doing something wrong?

**Comment by kengura** [comment]
Could you point me out to some documentation or examples?

**Comment by kpgalligan** [comment]
It's not quite to the part you need yet for multiplatform, but I go into workers and freezing here: https://medium.com/@kpgalligan/kotlin-native-stranger-threads-c0cf0e0fb847

Future posts (this/next week?) are going to talk about how to structure this for multiplatform.

In your specific case, you can try calling 'freeze' on callback before sending to the queue:
https://github.com/kengura/kotlin_multiplatform/blob/master/platform-ios/src/main/kotlin/com/multiplatform/api/AsyncApi.kt#L8

However, depending on what you're planning to do, that could be problematic, and although I'm sleep deprived, it looks like your callback is going to return on a different thread than you sent it, which is kind of not how async callbacks generally work.

**Comment by kengura** [comment]
I cannot freeze callback. I was trying to change code:
```
actual fun asyncCall(callback: ApiCallback) {
    val frozen = callback.freeze()
    dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT.toLong(), 0)) {
        println("before callback invocation")
        frozen.result()
        println("after callback invocation")
    }
}
```
But i'm getting compile error"
```
> Task :platform-ios:compileKonanKMultiIos_x64 FAILED
platform-ios/src/main/kotlin/com/multiplatform/api/AsyncApi.kt:8:31: error: unresolved reference: freeze
        val frozen = callback.freeze()
```

Actually there is no issue with callback. I can remove its invocation, but problem still there.
```
actual fun asyncCall(callback: ApiCallback) {
    dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT.toLong(), 0)) {
        println("Hello")
    }
}
```
 I'm sure there is an issue with releasing lambda object in `FreeContainer(ContainerHeader*)`

**Comment by kpgalligan** [comment]
I assume you can't call 'freeze' because you didn't import it.

import konan.worker.freeze

You will definitely have issues with 'callback' in the future. I assume you'll be capturing data from one thread and trying to operate on it in another, along with 'callback' itself. That will occasionally fail. At best it'll fail regularly. Worse, it'll only fail occasionally.

However, yeah, it kind of makes sense that you're having trouble with lambda. I haven't tried calling iOS threads, but I'm guessing the lambda itself is an object reference.  In summary, KN and threads is nontrivial. For this example, you can use a worker, as you're not trying to post back to the main thread.

Without too much detail, KN doesn't do atomic reference counting for 'hot' data, so just moving it between threads is going to be painful. You will occasionally get double calls to remove data when the increment doesn't go as planned. I haven't tried this at all, but maybe you could call freeze on the lambda? In any case, I'd highly encourage a deeper dive into KN threads (which I'm also doing now).

**Comment by kengura** [comment]
Thanks for clarification. It appears i should solve multi-threading tasks with KN idiomatic approaches. I think task can be closed.
