### ISSUE TITLE
EXC_BAD_ACCESS (code=EXC_I386_GPFLT) crash on GC using MacOS native API

### ISSUE THREAD

**Issue by soywiz** [JetBrains/kotlin-native#1780]
![screen shot 2018-07-09 at 02 49 35](https://user-images.githubusercontent.com/570848/42425903-0f2d0696-8323-11e8-8b90-39e1b6764a70.png)

This branch:
https://github.com/korlibs/korlibs/tree/native.error.on.gc.using.macos.native.api

To reproduce:
```
./gradlew clean install
cd samples
../gradlew :sample1-native:compileDebugMacos_x64KotlinNative
sample1/native/build/exe/main/debug/macos_x64/sample1-native.kexe
```

**Comment by olonho** [comment]
Problem look similar to https://github.com/JetBrains/kotlin-native/issues/1748 in this case on instance of com.soywiz.korag.AGNative. When walking over fields of AGNative instance field 16th, onReady we get
```
(lldb) p (void*)Konan_DebugGetFieldAddress(0x101a51738, 16)
(void *) $42 = 0x0000000101a517c8
(lldb) p (char*)Konan_DebugGetFieldName(0x101a51738, 16)
(char *) $43 = 0x00000001003cc641 "onReady"
(lldb) x/2g 0x0000000101a517c8
0x101a517c8: 0x3ff0000000000000 0x0000000101a51908
```
Looks like some other module wrote 0x3ff == 1023 on place, where `onReady` callback is expected. This likely happens due to fact that we see mismatching object layout in different libraries.

**Comment by homuroll** [comment]
Fixed in master.
