### ISSUE TITLE
error: unable to call non-designated initializer as super constructor

### ISSUE THREAD

**Issue by ildarsharafutdinov** [JetBrains/kotlin-native#1995]
hi,

I try to use https://github.com/TextureGroup/Texture/blob/master/Source/ASViewController.h from kotlin native and get `error: unable to call non-designated initializer as super constructor`.

Here is extract from `ASViewController.h`:
```
@interface ASViewController<__covariant DisplayNodeType : ASDisplayNode *> : UIViewController <ASVisibilityDepth>

...
- (instancetype)initWithNode:(DisplayNodeType)node;
...
```

klib stubs contain `designated = false` for `initWithNode:`:
```
        @ObjCConstructor(designated = false, initSelector = "initWithNode:") constructor(node: ASDisplayNode?)
        @ObjCConstructor(designated = true, initSelector = "initWithNibName:bundle:") constructor(nibName: String?, bundle: NSBundle?)
        @ObjCConstructor(designated = true, initSelector = "initWithCoder:") constructor(coder: NSCoder)
        @ObjCConstructor(designated = false, initSelector = "init") constructor()
```

The intended usage is to inherit from `ASViewController` and then call `initWithNode:` from the successor:
https://github.com/TextureGroup/Texture/blob/master/examples/ASViewController/Sample/ViewController.h
https://github.com/TextureGroup/Texture/blob/master/examples/ASViewController/Sample/ViewController.m

However, `initWithNode:` is marked as `designated = false` which makes the lib hardly usable.
I guess `designated = false` is incorrect at least in the case described above.

**Comment by SvyatoslavScherbina** [comment]
This behaviour is intentional: calling non-designating initializer as super constructor is incorrect and may lead to unpredictable results.
Swift has the same restriction for the same reasons, and I believe that it is not possible to write such code in Swift.
Btw, in master branch of this library the issue is already fixed: https://github.com/TextureGroup/Texture/commit/847884a7b463aede869d3d850fd4548d8f817073

You can workaround the issue by using `disableDesignatedInitializerChecks` def file option as described here: https://github.com/JetBrains/kotlin-native/blob/master/OBJC_INTEROP.md#subclassing-swiftobjective-c-classes-and-protocols-from-kotlin

**Comment by ildarsharafutdinov** [comment]
This exact version(2.7) works fine in swift.

I'll try `disableDesignatedInitializerChecks`, thank you.

**Comment by SvyatoslavScherbina** [comment]
> This exact version(2.7) works fine in swift.

Yes, you are right: Swift seems to use rules a bit less strict than Kotlin/Native ones: if an Objective-C class doesn't have an `NS_DESIGNATED_INITIALIZER`, then Swift compiler considers all of its initializers designated, while Kotlin/Native doesn't.

**Comment by LouisCAD** [comment]
@ildarsharafutdinov Do you still need to have `disableDesignatedInitializerChecks` enabled?

I'm trying to subclass `UIViewController` and have the ability to instantiate it with zero parameters, to get to this: https://medium.com/ios-os-x-development/ios-start-an-app-without-storyboard-5f57e3251a25

**Comment by ildarsharafutdinov** [comment]
The question was related to `ASViewController` from a particular version of `Texture` lib. I'm not sure if `disableDesignatedInitializerChecks` is required now or not.

**Comment by LouisCAD** [comment]
It seems to still be, but I don't know where I have to put it.

**Comment by SvyatoslavScherbina** [comment]
@LouisCAD 

> I'm trying to subclass UIViewController and have the ability to instantiate it with zero parameters,

Does the same work with Swift?

**Comment by LouisCAD** [comment]
@SvyatoslavScherbina As can be seen in the screenshots from [the official documentation here](https://developer.apple.com/library/archive/referencelibrary/GettingStarted/DevelopiOSAppsSwift/WorkWithViewControllers.html), you can subclass `UIViewController` in Swift, without having to call nor override the initializers.

That's something Kotlin doesn't permit as it requires to call the super constructor, which then leads to the error from this issue.

Trying to override all the initializers doesn't help.

This compiles:
```kotlin
@ExportObjCClass
class OldViewController : UIViewController {

    @OverrideInit
    constructor(coder: NSCoder) : super(coder)

    @ObjCOutlet
    lateinit var label: UILabel

    @ObjCOutlet
    lateinit var textField: UITextField

    @ObjCOutlet
    lateinit var button: UIButton

    @ObjCAction
    fun buttonPressed() {
        label.text = "Konan says: 'Hello, ${textField.text}!'"
    }
}
```
but you can't instantiate it programmatically if you were to try to break free from storyboards since you no longer have an argument-free constructor.

If you add the following:
```kotlin
    @OverrideInit
    constructor() : super()
```
the IDE stops complaining, but compilation still fails with the non-designated initializer error.

**Comment by SvyatoslavScherbina** [comment]
Then your problem is not related to the original fixed issue.
See #2010 instead.
