### ISSUE TITLE
konan.configuration.build.dir stopped working

### ISSUE THREAD

**Issue by yuriry** [JetBrains/kotlin-native#2099]
I specify **-Pkonan.configuration.build.dir="$CONFIGURATION_BUILD_DIR"** in an iOS project [as described here](https://github.com/JetBrains/kotlin-native/blob/master/MULTIPLATFORM.md#user-content-4-ios-application) but after migrating to kotlin/native 0.9 it seems to stop working.  When I import my module into a swift file, Xcode complains that the module is not found.  
When I run ```gradlew compileDebugIos_arm64KotlinNative -Pkonan.configuration.build.dir=foo```
from a command line, it has no effect - output goes to build folder instead.  The same happens when Xcode runs a custom build phase - the framework is built, but the output goes to the build folder of the Kotlin/Native-iOS project instead of to $CONFIGURATION_BUILD_DIR.

If I manually copy generated framework from build folder to $CONFIGURATION_BUILD_DIR, Xcode compiles and runs my iOS application.  I'm using Xcode Version 9.4.1 and [the experimental plugin](https://github.com/JetBrains/kotlin-native/blob/master/GRADLE_PLUGIN.md#experimental-plugin)

Is is a known issue?

Thank you in advance!

**Comment by ilmat192** [comment]
Yes, the experimental plugin doesn't use these project properties. But you can copy the framework in the right location as shown [here](https://github.com/JetBrains/kotlin-mpp-example/blob/master/greeting/ios/build.gradle). 

Such an approach is preferable than producing a framework right into the configuration directory because in this case compile task behaviour has no implicit dependencies on external parameters. Of course writing a copy task in a buildscript is pretty inconvenient so we'll consider generating such tasks/XCode projects by the plugin.

**Comment by yuriry** [comment]
This is great, thank you for the quick reply!

I slightly modified build script to also pass $KONAN_TASK as konan.configuration.build.task property so that copyFramework copies output files from the current task instead of the files from compileDebugIos_x64KotlinNative task. Everything else is as in the kotlin-mpp-example project.

```gradle
task copyFramework() {
    doLast {
        def task = getProperty("konan.configuration.build.task")
        def srcFile = tasks[task].outputFile
        def targetDir = getProperty("konan.configuration.build.dir")
        copy {
            from srcFile.parent
            into targetDir
            include '*.framework/**'
            include '*.framework.dSYM'
        }
    }
}
```
