### ISSUE TITLE
Google Fucshia OS support

### ISSUE THREAD

**Issue by fadi-botros** [JetBrains/kotlin-native#2267]
I think we would need someday to support the new system by Google (Fucshia) https://fuchsia.googlesource.com/fuchsia/, so that we could get a thread-safe multi-threaded language to deal with performance problems caused by strictly single-threaded nature of Flutter.

I think as you could export your code into C, and make it fully interoperable with C, this wouldn't be a hard task, just the standard library would need to change (Fucshia is NOT Linux, it is a whole new kernel called Zircon, we could treat it as another platform like what you have done with iOS).

Also the interoperabillity in that system is done with a Rosetta Stone system called FIDL https://fuchsia.googlesource.com/docs/+/master/development/languages/fidl/, so, as much as you can export C functions and define them using it, it would be fully interoperable in Fucshia.

**Comment by olonho** [comment]
We may consider contributions adding Fucshia support, but unlikely invest efforts into doing that on our own soon.

**Comment by sbogolepov** [comment]
We are migrating issues to YouTrack and since Fuchsia future is still unclear, we won't work on this target in the foreseeable future. So I'm closing this issue. However, if you think this target is important and you see how Kotlin/Native can be useful there, you can describe the use-case in [KT-43974](https://youtrack.jetbrains.com/issue/KT-43974).
