### ISSUE TITLE
Destructor

### ISSUE THREAD

**Issue by kylejbrock** [JetBrains/kotlin-native#2327]
In Java, there is the finalize method to know when a class is being GC'd.  Is there a mechanism in K/N for doing something similar?  

The situation I'm in is I have some native resources that I want to be allocated only for the lifecycle of another object.  But, there's no clear way to know when that object is going to be deallocated (that I'm seeing).

Thanks!

**Comment by kylejbrock** [comment]
I see.  How open are you all at this point to external pull requests?  Specifically, someone implementing some sort of deinit method.  The potential solutions mentioned in the stackoverflow article seem insufficient for what I need.  I'm open to adding this type of functionality, but I don't want to waste your time or mine if you're not interested in this type of feature (though, I hope you are).

Thanks!

**Comment by olonho** [comment]
Nope, we believe that general-purpose deinit functions bound to the object lifetime are both error-prone and hard to implement correctly.

**Comment by kylejbrock** [comment]
Then, what is the best way to deallocate c-interop resources that are held by a kotlin object if there's no way of knowing when the kotlin object is going to be deallocated?  Keep in mind, I'm not referring to scope bound lifecycles.  I'm going to need some help wrapping my head around this.

WeakReferences don't inform when something is being deallocated.

If there is a c function that must do some tear down of a c-pointer before it's memory can be deallocated, it's unclear to me how that would be done without some sort of reference counting (which breaks down when you're using kotlin multi-platform).

So far, all of the examples of memory management are scope based.  And, in practice there are lots of problems dealing with memory management that are not scope bound.  The appeal of kotlin/native, at least for me, is it's ability to interop with c/obj-c + multi-platform.  This approach seems like a limiting factor in leveraging that ability in an idiomatic way.  And without the ability to be informed of a single object's lifecycle, the complexity to deal with those types of problems grows exponentially.  Unless, of course, there's a facility already available for solving this that I'm not aware of.

**Comment by olonho** [comment]
Deallocation of objects in systems with automated memory management can happen very late or (in theory) even never. So only pure memory bound resources could be managed this way, everything else better have clear lifecycle (i.e. arena-like grouping or explicit scoped usage). It was an explicit design decision to not expose general-purpose mechanisms for that. but for Kotlin peers of Objective-C objects deinit hooks may help.

**Comment by realh** [comment]
Without destructors it makes it harder to generate bindings from gobject-introspection that have robust memory management without forcing users to manage the memory themselves as if they were writing in plain C. It could be possible to prevent this by making GObjects manage the lifetime of their Kotlin wrappers instead of the other way round, but GObject-based code usually uses lots of other simpler structs and pseudo-classes that would be harder to deal with than in other managed languages.

In case you haven't heard of GObject(Introspection), it's a C library with an object model and set of conventions for writing and annotating C. There's a rich collection of libraries that use it, including Gtk and GStreamer. Its object model is very close to Kotlin's, so I think combining the two would have a lot of mutual benefits.
