### ISSUE TITLE
iOS: dSYM for release build?

### ISSUE THREAD

**Issue by zydeco** [JetBrains/kotlin-native#2422]
Is it possible to have a dSYM generated for release builds?
This would allow getting symbolicated crash logs from release apps.

I though I could do this on [`MacOSBasedLinker.linkCommands`](https://github.com/JetBrains/kotlin-native/blob/70e6b711349cf3a5bd937b6fcec124d2ca1244ef/shared/src/main/kotlin/org/jetbrains/kotlin/konan/target/Linker.kt#L132-L158):
 - removing `linkerNoDebugFlags` from the main linker command
 - always adding `dSymUtilCommand`
 - adding a `strip` command if debug is false

However, the resulting dSYM is still missing some symbols, I guess they're optimized out earlier?

**Comment by benasher44** [comment]
I just tried this and got the same result. The generated `linkReleaseFrameworkIos` task generates no .framework.dSYM while the generated debug variant `linkDebugFrameworkIos` does generate a .framework.dSYM. is there a workaround for this, or some setting that we should be paying attention to?

**Comment by benasher44** [comment]
Hi @olonho! I think the change to fix this is to just remove the conditional `if (debug)` check here: https://github.com/JetBrains/kotlin-native/blob/master/shared/src/main/kotlin/org/jetbrains/kotlin/konan/target/Linker.kt#L157

For release builds, the dSYM file is needed to be avaiable to make sense of crash reports from production builds. In debug builds, the dSYM file is often needed by profiling tools. If permanently enabling this feels irresponsible, maybe we could add a flag that controls dSYM generation here; it could default to what it does today (or maybe to just release builds only, since that's what you want in most environments where you intend to ship the framework in production)?

Sorry if you're the wrong person to ask! I found you from #1515, which I believe is the last time this was touched.

**Comment by benasher44** [comment]
> adding a strip command if debug is false
This would also be nice ^

**Comment by idstein** [comment]
This issue is really important to run a app productive and de-crypt stack traces! Please add an optional flag to generate DSYM symbols for release frameworks.

**Comment by SvyatoslavScherbina** [comment]
> Please add an optional flag to generate DSYM symbols for release frameworks.

#3154 looks much like this (still draft though).

Also some efforts are required to make the ("encrypted") stack trace itself more verbose.

**Comment by franmowinckel** [comment]
Just noticed that the release binary is smaller than the debug one... which makes me think if it's not that they're swapped? I mean, the debug one looks like the release one and vice-versa.

**Comment by benasher44** [comment]
It should be smaller, since symbols will be stripped from the binary + optimizations can have size impact (albeit both ways)

**Comment by SvyatoslavScherbina** [comment]
Btw, has anybody tried related new features in 1.3.60 EAP 2?
More details available here: https://github.com/JetBrains/kotlin-native/blob/master/IOS_SYMBOLICATION.md

**Comment by benasher44** [comment]
Not yet. Testing us hard for us because we have to recompile 7 libraries to test EAP 😬

**Comment by franmowinckel** [comment]
> It should be smaller, since symbols will be stripped from the binary + optimizations can have size impact (albeit both ways)

@benasher44  Sorry, my bad, I was meaning the opposite, the framework binary in the `debugFramework` is actually smaller (~1.1M in my case) and contains the dSYM, but the one in the `releaseFramework` is bigger (~2.7M) and contains no dSYM. So that's why I'm asking if it's not that they're swapped?

**Comment by benasher44** [comment]
Great question! Can you create a new issue?
