### ISSUE TITLE
IncorrectDereferenceException threading in Swift

### ISSUE THREAD

**Issue by Reedyuk** [JetBrains/kotlin-native#2470]
I have an issue with my Kotlin Multiplatform project, I created my data models in a shared project (in my github example i called this Concurrency), then when i run this in my iOS project and access the variable from multiple threads, i'm getting the following exception:

> Uncaught Kotlin exception: kotlin.native.IncorrectDereferenceException: illegal attempt to access non-shared sample.Concurrency@1f64468 from other thread

I **need** to be able to access variables concurrently from different threads in Swift, especially as i use AsyncDisplaykit in my project, which is always jumping from threads.

Here is a link to the issue i am facing:
[https://github.com/Reedyuk/Concurrency-Issue-Kotlin-Native](https://github.com/Reedyuk/Concurrency-Issue-Kotlin-Native)
Open the iOS-Example folder and run to get the issue, or open the whole folder in intelij and run buildForXcode and copy the framework file across into the ios project.

**Comment by Coneys** [comment]
I have same issue in my project. Only working way for now was to freeze my objects, and then make a copy on another thread, but there has to be another easy way to do it. 
You can check this [issue](https://github.com/JetBrains/kotlin-native/issues/2443), maybe you will figure out  how to apply olonho's solution into Swift world.

**Comment by talanov** [comment]
You have to "freeze" your instances with kotlin.native.concurrent.

But, I guess, neither "@SharedImmutable" nor ".freeze()" are avail in mpp projects ¯\_(ツ)_/¯

**Comment by Coneys** [comment]
Well the problem is, sometimes you don't want to freeze object, but pass it to another thread (and change thread that owns this object). I tried to do it with DetachedGraphObject, but it didn't work (I don't want to use Workers, I would like to call DispatcherQueue from Swift, then detach graph and attach it on main thread)

**Comment by mikezliu** [comment]
I'm stuck trying to accomplish a basic scenario. I have an interface defined in KN MPP that accepts a callback (which is created in KN). This interface is implemented on iOS and launches a background worker, does some processing, then calls the callback when done.

I'm running into IncorrectDeferenceException because the callback is defined in KN.  So I've tried:

1) freezing the callback. However when I freeze the callback, it seems to freeze all the parent objects (I guess because they belong in the same subgraph), causing unavoidable errors elsewhere since the parent objects are managers kept around for the lifecycle of the app.

2) On iOS, I tried calling DispatchQueue.main.async before calling the KN callback. However this still gives me an error: IncorrectDereferenceException: illegal attempt to access non-shared <object>@38d1358 from other thread

3) On iOS, use semaphore or other locking mechanisms to wait for the background operation to finish, and then call the callback.  But since KN runs on the main thread, this freezes all UI on the iOS app until the background work is done

I'm kind of stuck on how I can proceed. The background worker needs to run on iOS and isn't possible to run on KN.  Any ideas?  Thanks

**Comment by alandoni** [comment]
did you accomplish this @Coneys ? I am trying to do exactly the same thing

**Comment by Coneys** [comment]
No, I gave up. For now Kotlin Native and threading system is too complicated. It is faster for us to duplicate code on iOS and Android ;/

**Comment by soundbites** [comment]
We are having the exact same problem. Can you guys add the @SharedImmutable" or ".freeze()" features to MPP?

Btw. All our data is immutable so if it is easier to grant us read-only access on Kotlin objects in threads other then the Main thread that would be awesome.

**Comment by kar** [comment]
Any updates on this? Is there no way to use freeze() in Kotlin MPP?

**Comment by SvyatoslavScherbina** [comment]
About our plans: https://blog.jetbrains.com/kotlin/2020/07/kotlin-native-memory-management-roadmap/
YouTrack issue: https://youtrack.jetbrains.com/issue/KT-42296

> Can you guys add the @SharedImmutable" or ".freeze()" features to MPP?

Not sure if it is possible to make this entirely correctly, because there are no alternatives to these features on other platforms, and using dummy implementation might be confusing.
Trivial workaround is to declare these in your project.
