### ISSUE TITLE
OpenGL on Linux state?

### ISSUE THREAD

**Issue by pavlus** [JetBrains/kotlin-native#2511]
I see that OpenGL bindings are available for all supported platforms except Linux, should we expect them to come, support is not planned, there are some difficulties, help wanted, or something else?

**Comment by Dominaezzz** [comment]
The only reason there are any OpenGL apis available on windows and macos is because the (limited) api calls ship with the platform, allowing Kotlin/Native to easily expose them as platform libraries.
Linux being linux, doesn't ship with any by default.
OpenGL support will have to be provided by a separate library like glew, glad, glagogen, etc.

**Comment by SvyatoslavScherbina** [comment]
Correct.
