### ISSUE TITLE
Documentation for GC

### ISSUE THREAD

**Issue by binary132** [JetBrains/kotlin-native#2516]
Where can I find public-facing (_not a comment in a source file, or implementation source code_) documentation about the GC implementation in Kotlin/native?  When disabling the GC, what happens to orphaned references?

**Comment by diegomontoya** [comment]
Just go search "GC" on the repo and you will find lots of code directly related to GC. 

It would be better to reframe the question to a specific file/spec on GC that is confusing or missing docs.

**Comment by velavokr** [comment]
I think what is being asked is is there a design document for the memory management system in kotlin native? 

One of the topics one might expect to be covered there is for example how the memory management runtime should handle the allocations and object lifecycles in native (C/C++) libraries. Another is the finalization of nonmemory resources (should eg the dangling file descriptors be closed by the runtime and if so when should that happen)

**Comment by velavokr** [comment]
Actually some of the answers are implicitly presented here 
https://github.com/JetBrains/kotlin-native/blob/master/INTEROP.md

**Comment by SvyatoslavScherbina** [comment]
The initial request is too generic to be covered by anything except for the code itself.

> When disabling the GC, what happens to orphaned references?

Please don't do this. This is internal API, and in fact it is not maintained.

Feel free to ask more specific questions. Please consider using alternative platforms for the questions, since we are [migrating](https://github.com/JetBrains/kotlin-native/issues/4079) everything from GitHub issues.
