### ISSUE TITLE
Error accessing companion object members from Swift

### ISSUE THREAD

**Issue by philmitchell** [JetBrains/kotlin-native#2571]
From Swift, I try to access the companion object like this:

```swift
let p = Ping.Companion()
let d = p.NO_DISTANCE
```

The compiler error (Swift 4.2):
```
'NO_DISTANCE' has been renamed to 'no_DISTANCE'
'NO_DISTANCE' was obsoleted in Swift 3
```

Sure enough, I am able to access it like this:

`let d = p.no_DISTANCE`

Here is the Kotlin code:

```kotlin
data class Ping(
    val id: String,
    val distance: Double,
    val rssi: Int
) {
    companion object {
        const val NO_DISTANCE: Double = -1.0
        const val NO_RSSI: Int = 10000
    }
}
```

Here is the relevant section from the library header file:

```Objective-C
__attribute__((objc_subclassing_restricted))
__attribute__((swift_name("Ping.Companion")))
@interface MyLibPingCompanion : KotlinBase
+ (instancetype)alloc __attribute__((unavailable));
+ (instancetype)allocWithZone:(struct _NSZone *)zone __attribute__((unavailable));
+ (instancetype)companion __attribute__((swift_name("init()")));
@property (readonly) double NO_DISTANCE;
@property (readonly) int32_t NO_RSSI;
@end;
```

**Comment by SvyatoslavScherbina** [comment]
Thank you for the report.

The issue is not specific to companion objects and caused by name translation rules applied when importing Objective-C to Swift. Swift lowercases names of Objective-C properties, so `NO_DISTANCE` becomes `no_DISTANCE`.
To be fixed for Kotlin by adding explicit `swift_name` attributes to properties in the header.
