### ISSUE TITLE
Crash using object as singleton with cinterop (SDL)

### ISSUE THREAD

**Issue by arpie42** [JetBrains/kotlin-native#2619]
Should this work?  I think it should work.

Is it a compiler bug?  Have I misunderstood object singletons?

In any case, as written it crashes on Linux (and also on Android) with the error :
```
Uncaught exception from Kotlin's main: kotlin.native.concurrent.InvalidMutabilityException: mutation attempt of frozen sample.Graphics@1ac6798
```
at the line :
```
win = SDL_CreateWindow("MyWindow", 0, 0, 640, 480, (SDL_WINDOW_SHOWN))
```
To prevent the crash, either :
1) 'fun init(){' can be replaced with 'init{';
2) or object Graphics can be refactored as a class and instantiated in main().

But I don't want to do either of those things.  I want a singleton.  Mostly I want to understand why it is crashing.

I've pushed a repo with the cinterop and gradle setup so you can just do 'gradle runProgram' here: https://github.com/arpie42/kn-obj-test
```
package sample

import kotlinx.cinterop.*
import platform.posix.*
import sdl.*

fun main(args: Array<String>) {
    Graphics.init()
    Graphics.run()
    Graphics.exit()
}

fun get_SDL_Error() = SDL_GetError()!!.toKString()

object Graphics {
    private var win:CPointer<SDL_Window>? = null
    private var ren:CPointer<SDL_Renderer>? = null

    fun init() {
        println("start init")
        if(SDL_Init(SDL_INIT_EVERYTHING) == -1) {
            println(" !! ERROR !! SDL_Init: ${ get_SDL_Error() }")
        }
        win = SDL_CreateWindow("MyWindow", 0, 0, 640, 480, (SDL_WINDOW_SHOWN))
        if (win != null){
            println(" !! OK !! SDL_CreateWindow")
        }else{
            println(" !! ERROR !! SDL_CreateWindow: ${ get_SDL_Error() }" )
        }
        ren = SDL_CreateRenderer(win, -1, SDL_RENDERER_ACCELERATED or SDL_RENDERER_PRESENTVSYNC)
        if (ren != null){
            println(" !! OK !! SDL_CreateRenderer")
        }else{
            println(" !! ERROR !! SDL_CreateRenderer: ${ get_SDL_Error() }" )
        }
        println("SDL_Success: ${ get_SDL_Error() }" )
    }

    fun run(){
        var done = false
        memScoped {
            val event = alloc<SDL_Event>()
            val eventPtr:CValuesRef<SDL_Event> = event.ptr.reinterpret()
            while(!done){
                while (SDL_PollEvent(eventPtr) != 0) {
                    val eventType = event.type
                    if(eventType == SDL_QUIT || eventType == SDL_KEYDOWN) {
                        done = true
                    }
                }
            }
        }
    }

    fun exit() {
        SDL_DestroyRenderer(ren)
        SDL_DestroyWindow(win)
        println("Bye")
        SDL_Quit()
    }
}
```

**Comment by kylejbrock** [comment]
K/N "object" classes are immutable.  So, once the class's constructor is called, the object is frozen.

Using "init" vs "init()" is the different between using the constructor vs a function.  When using the constructor, the object isn't frozen.  When using the function, the object is frozen.  And, as such, immutable.

Using a "class" instead of "object" is the difference between the class not being immutable immediately vs it being immutable immediately.

Take a look at AtomicReference.  Using it would allow you to keep the singleton model.

Some important things to read:
https://github.com/JetBrains/kotlin-native/blob/master/IMMUTABILITY.md
https://github.com/JetBrains/kotlin-native/blob/master/CONCURRENCY.md

**Comment by arpie42** [comment]
That's exactly the sort of answer I was hoping for, thank you!
