### ISSUE TITLE
Run & compile Calculator Sample

### ISSUE THREAD

**Issue by cosminstefanxp** [JetBrains/kotlin-native#2843]
I'm trying to run the Calculator Sample only, on a MacOS. It seems that if I import the entire project in Android Studio and then run  `./gradlew build`, I'm getting the following issue:

```
Execution failed for task ':arithmeticParser:compileKotlinIos'.
> Classpath of the tool is empty: konanc
  Probably the 'org.jetbrains.kotlin.native.home' project property contains an incorrect path.
  Please change it to the compiler root directory and rerun the build.
```

How can I correctly install / set up `konanc`? Shouldn't it have been brought as a dependency by the sample project's gradle config? How should I download and install it?

TLDR: Is there any sample project that we can simply download/clone, follow some instructions for installing compiler (e.g. `brew install kotlinc`?) and run on both iOS and Android?

**Comment by ilmat192** [comment]
It's because by default samples in the Kotlin/Native repo use the compiler built from sources. So you need to build it first. 

Alternatively you may just remove the [line](https://github.com/JetBrains/kotlin-native/blob/540fd65a28fce2bec112555776256aa6d4cb2dd6/samples/calculator/gradle.properties#L4) which overrides the path to the compiler. After that a default compiler for this Gradle plugin version will be downloaded and used to build the sample.

> Is there any sample project that we can simply download/clone, follow some instructions for installing compiler (e.g. brew install kotlinc?) and run on both iOS and Android?

Yes, you can take a look at [this](https://github.com/JetBrains/kotlin-mpp-example) example.

Also you can explore [this](https://kotlinlang.org/docs/tutorials/native/mpp-ios-android.html) tutorial. Its source code is available at GitHub so you can clone it and play with it. Note that the tutorial requires using Kotlin 1.3.0 because it relies on a binary naming scheme which was changed in 1.3.20. But the main approach remains the same.

**Comment by cosminstefanxp** [comment]
Thank you. It would be great if the info you've provided here (especially about the `org.jetbrains.kotlin.native.home`) would be also present in the main Samples Readme.

**Comment by ilmat192** [comment]
The readme mentions that the compiler must be built first. But it doesn't mention using the `org.jetbrains.kotlin.native.home` property so it makes sense to add such an information in the readme.

**Comment by ilmat192** [comment]
Added such a mention: https://github.com/JetBrains/kotlin-native/commit/745b99a61eacf570fcc280991bdc4c5225e5cf53.
