### ISSUE TITLE
type CValue<simd_float4x4> of return value is not supported here: not a structure or too complex

### ISSUE THREAD

**Issue by idstein** [JetBrains/kotlin-native#3010]
Unable to use simd_ type definitions from iOS.

We can properly integrate with ARKit, receive ARFrame, but can not properly use ARCamera as its interface is defined using simd_ types. Those are either visible, like simd_float4x4, but do not show in the interop header any fields at all!
Other types such as simd_float2 or simd_float3 are not visible at all and entire methods hence gone from the interop definitions.

**Comment by SvyatoslavScherbina** [comment]
Thanks for the report, this is known issue.

**Comment by idstein** [comment]
Is support planned for it? Are there any other known to be hidden C constructs?

**Comment by olonho** [comment]
Yes, support is planned, but no public ETA on that. Generally, most constructs of C shall be supported by now, if not - please report.

**Comment by knebekaizer** [comment]
#3602 mentioned above does a job of struct sending by value, but we still have problem with __ext_vector__ types (aka simd_float4):
`error: overload resolution ambiguity`
This is actually the issue of libclang which is fixed in the next (incoming) version. Still looking for suitable temporary workaround.

**Comment by SvyatoslavScherbina** [comment]
As answered above, sending this struct by value is supported.
