### ISSUE TITLE
How to set 'headerFilter' in build.gradle

### ISSUE THREAD

**Issue by DTHeaven** [JetBrains/kotlin-native#3245]
```
targets {
    configure(iosTargets) {
        compilations.main.cinterops() {
            create('entity_bridge') {
                compilerOpts(entityCompilerOptsValue)
                headers(headerFiles)
            }
        }
    }
}
```
This config not work.
How to config 'headers' and 'headerFilter' in build.gradle, without 'def' file.

**Comment by artdfel** [comment]
This option is unavailable now. We'll see if anything can be done here, please wait for updates.

**Comment by ilmat192** [comment]
@DTHeaven Could you please provide more details about your use-case? Why can't you specify `headerFilter` in a def-file?

> This config not work.

Could you please explain how exactly it doesn't work in your case? This DSL construction works correctly from the Gradle point of view so probably the issue is in your particular setup.

**Comment by SvyatoslavScherbina** [comment]
Setting `headerFilter` in `build.gradle` is not supported at the moment.
Please create a new issue in YouTrack and describe your use-case if this still affects you: https://kotl.in/issue
