### ISSUE TITLE
How to make a linux arm32 soft float target?

### ISSUE THREAD

**Issue by XQDD** [JetBrains/kotlin-native#3350]

**Comment by olonho** [comment]
android_arm32 is Linux soft-float target, for example.

**Comment by XQDD** [comment]
Is there a tutorial on how to edit it? For example which file need to edit and which resource need I to prepare?

**Comment by sbogolepov** [comment]
There is a hacky way to create a static library for a soft float arm32 target when compiling for `arm32_linux_hfp`. See [HACKING.md](https://github.com/JetBrains/kotlin-native/blob/master/HACKING.md#playing-with-compilation-pipeline).
For example, by providing `-Xoverride-clang-options=-cc1,target-cpu,cortex-a8,-mfloat-abi,soft,emit-obj,-disable-llvm-optzns,-x,ir` compiler option when producing static library for `linux_arm32_hfp` you will get a static library for soft float arm32. Creation of dynamic library or executable involves linkage with files from sysroot for `linux_arm32_hfp` which will result in incorrect binary. But you can create a PIC binary by passing `-mrelocation-model pic` to Clang and then use an appropriate toolchain to create a dynamic library. 
Since we are [migrating to YouTrack](https://github.com/JetBrains/kotlin-native/issues/4079), I'll close the issue. Feel free to create a new one at https://kotl.in/issue!
