### ISSUE TITLE
about FatFrameworkTask Issue 

### ISSUE THREAD

**Issue by cydhhp** [JetBrains/kotlin-native#3605]
Hi
Because I want to manager and separate my customer task
so I create ios.gradle.kts file
```
import org.jetbrains.kotlin.gradle.tasks.FatFrameworkTask 
......


tasks.create(".....", FatFrameworkTask::class){
........
}
```
it looks ok
then after build I got error **Unresolved reference: jetbrains**

but if those code in build.gradle.kts
it is fine

Is it only in build.gradle.kts??

Thanks

**Comment by artdfel** [comment]
Hello! It seems like the problem here is more about Gradle rather than Kotlin/Native. Please keep in mind, that the GitHub issues are for Kotlin/Native specific reports. 
 By default, every project is set to utilize `build.gradle(.kts)` file as buildFile. To change it, one has to specify this setting in the separate `settings.gradle(.kts)` file somehow like
```
rootProject.buildFileName = "my.gradle.kts"
```
Please try this approach.
