### ISSUE TITLE
Unable to access kotlin.native.Platform

### ISSUE THREAD

**Issue by binkley** [JetBrains/kotlin-native#3680]
Hi, I'm trying a spike project on Kotlin Native, and wanted my "hello world" to print out from what platform/target it is running.  I browsed into `kotlin.native.Platform` from IntelliJ as found in "kotlin-stdlib-native-sources.zip".  It's a ordinary looking file, no special access restrictions, etc.

I can read about `Platform` and it's ilk in the stdlib documentation: https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.native/index.html.

However, I am unable to import any symbols from `Platform`.

I've hunted about for a possible missing dependency without success (and poked at something like "kotlin-stdlib-common-native", matching the src.zip file, again without success).

It is interesting that there is "jvm" as a path component in the doc URL, so perhaps this is an unsupported feature on non-JVM platforms/targets.

This issue is possibly one of documentation.  Any suggestions?

**Comment by olonho** [comment]
Try to use it in Native specific source set, for example create new Native project with New Project Wizard in IDEA.

**Comment by binkley** [comment]
@olonho Thank you.  However, there are no particular dependencies listed in the generated `build.gradle` when using IntelliJ IDEA to create a fresh Kotlin native project.

**Comment by artdfel** [comment]
Hello @binkley! Sorry for such a long silence, let's see what can be done here. The problem here is more about how IDE understands the projects rather than a particular part of the standard library. 
I've seen your `spikes` repository, and if we're talking about the [kotlin-native](https://github.com/binkley/spikes/tree/master/kotlin-native) part, I should give some advice.
   As you use `kotlin-multiplatform` plugin here, the IDE always assumes that common source sets will be shared among all Kotlin flavors - Native, JVM, and JS. So, the only common part of the standard library is available there. It can be found under a blue mark in the stdlib reference. Actually, you can compile and run with native-specific imports, but the IDE will highlight them as undefined. Just add import in your `hello.kt` and execute `runReleaseExecutableMacosX64` task. 

 To use a native part of the Kotlin-stdlib more convenient way, one has to define a native source set, as mentioned above. In fact, you already have them in your project - macosX64Main, linuxX64Main, etc. If you will back them with a correct project structure (like `kotlin-native/src/macosX64Main/kotlin/<Filename>.kt`), it will be possible to use `kotlin.native.Platform` correctly from there. Stdlib contents will be visible for the IDE, and highlighting should also become fine. No additional dependencies needed.
I hope this explanation will help you a bit. This multiplatform thing can be unintuitive, so feel free to ask here or in the Kotlin Slack.

**Comment by binkley** [comment]
@artdfel What a helpful and clear explanation, thank you!

I'll close this issue, and try your suggestions.
