### ISSUE TITLE
Crash when use parameter in println

### ISSUE THREAD

**Issue by kavanmevada** [JetBrains/kotlin-native#3749]
Why it crash with this
```
dispatch("Hello") {
        println("Printing $it from Thread Started \n")
    }
```

and not with this ?
```
dispatch("Hello") {
        println("Printing from Thread Started \n")
    }
```

Code:
```
fun <P, T> dispatch(param: P, block: (P) -> T) {
    val ref = StableRef.create(param to block)
    pthread_create(nativeHeap.alloc<pthread_tVar>().ptr, null, staticCFunction { data: COpaquePointer? ->
        data?.asStableRef<Pair<P, (P) -> T>>()?.get()?.let { it.second.invoke(it.first.freeze()) }
        NULL
    }.reinterpret(), ref.asCPointer())
    ref.dispose()
}
```

**Comment by artdfel** [comment]
Hello, @kavanmevada! The problem here seems to be already solved by adding `initRuntimeIfNeeded()`, so let's try to dig a few into the reasons of it. I've made a look at [this](https://kotlinlang.slack.com/archives/C3SGXARS6/p1578586695042200) thread from the Slack. While playing with this snippet:
```
fun <P, T> dispatch(param: P, block: (P) -> T) {
    val pair = (param to block).freeze()
    val ref = StableRef.create(pair)
    pthread_create(nativeHeap.alloc<pthread_tVar>().ptr, null, staticCFunction { data: COpaquePointer? ->
        //initRuntimeIfNeeded()
        data?.asStableRef<Pair<P, (P) -> T>>()?.get()?.let { it.second(it.first) }
        NULL
    }.reinterpret(), ref.asCPointer())
    sleep(6)
    ref.dispose()
}
```
I realized, that without explicit runtime initialization the code crashes depending on the string size! By default, `StringBuilder`s capacity is equal 10.  If you are trying to print something small enough, like `println("$it :D")` for example, everything goes fine. But when you ask to build a few longer string, as in your case, `StringBuilder` got to extend itself, by allocating more space on the heap. But, as no runtime were initialized, this operation fails with `Segmentation Fault:11`. That caused the crash you faced.
Whenever you want to create a thread, always remember to initialize the runtime. There is an issue with some explanations [here](https://github.com/JetBrains/kotlin-native/issues/1448).

**Comment by kavanmevada** [comment]
> Hello, @kavanmevada! The problem here seems to be already solved by adding `initRuntimeIfNeeded()`, so let's try to dig a few into the reasons of it. I've made a look at [this](https://kotlinlang.slack.com/archives/C3SGXARS6/p1578586695042200) thread from the Slack. While playing with this snippet:
> 
> ```
> fun <P, T> dispatch(param: P, block: (P) -> T) {
>     val pair = (param to block).freeze()
>     val ref = StableRef.create(pair)
>     pthread_create(nativeHeap.alloc<pthread_tVar>().ptr, null, staticCFunction { data: COpaquePointer? ->
>         //initRuntimeIfNeeded()
>         data?.asStableRef<Pair<P, (P) -> T>>()?.get()?.let { it.second(it.first) }
>         NULL
>     }.reinterpret(), ref.asCPointer())
>     sleep(6)
>     ref.dispose()
> }
> ```
> 
> I realized, that without explicit runtime initialization the code crashes depending on the string size! By default, `StringBuilder`s capacity is equal 10. If you are trying to print something small enough, like `println("$it :D")` for example, everything goes fine. But when you ask to build a few longer string, as in your case, `StringBuilder` got to extend itself, by allocating more space on the heap. But, as no runtime were initialized, this operation fails with `Segmentation Fault:11`. That caused the crash you faced.
> Whenever you want to create a thread, always remember to initialize the runtime. There is an issue with some explanations [here](https://github.com/JetBrains/kotlin-native/issues/1448).
Perfect answer, thanks for explaining further "How initRuntimeIfNeeded() fix problem".
