### ISSUE TITLE
[Reverse C Interop] 1.3.70 headers use __attribute__, unsupported by MSVC

### ISSUE THREAD

**Issue by alusch** [JetBrains/kotlin-native#3953]
In 1.3.61, the generated header could be successfully compiled with MSVC out of the box. With 1.3.70, the `KVector128` type is now using the GCC-specific `__attribute__`, which MSVC does not support:

```
typedef float __attribute__ ((__vector_size__ (16))) knlibrary_KVector128;
```

You can work around by doing `#define __attribute__(x)`, but of course that loses the vector-ness and will crash if you try to actually use any vectors. Ideally the header would generate appropriate MSVC-specific code behind an `#ifdef`.

**Comment by sigmasoldi3r** [comment]
I came with that same problem for kotlin native `1.3.70`

Looking forward for a workaround too 👀 hehe

**Comment by artdfel** [comment]
Hello! AFAIK, we got no such option currently - because we utilize MinGW on Windows targets, which is compatible with GCC conventions, there is no chance we can generate MSVC header out-of-the-box.
The only possible option here can be a manual change of the generated header's content(precisely `__attribute__`) to the MSVC-compatible representation of vector types, hoping that ABI will be alike.

**Comment by PatrickLemke** [comment]
Do I understand correctly that MSVC is currently not supported even though the example in the documentation is using it?

**Comment by SvyatoslavScherbina** [comment]
According to [migrating issue tracking to YouTrack](https://github.com/JetBrains/kotlin-native/issues/4079), closing this issue in favour of https://youtrack.jetbrains.com/issue/KT-39258
