### ISSUE TITLE
Auto destructors pretty please

### ISSUE THREAD

**Issue by DrOptix** [JetBrains/kotlin-native#3983]
Please consider adding destruction.  It is a pain to having to manually call hand made "Destroy" methods. Well actually I did not implement that because I just started on a mini game engine project.

Maybe I have a too much C++/C# mindset, but I would really like to have something like a destructor and I think the use case I'm presenting is a valid one and should really be taken into consideration.

Or... is there some language construct I did not discover that would allow me to implement something on the lines of C++ smart pointers, but event for that I think a destructor is needed

My use case is like this and I would really like to be able to have some kind of auto destruction mechanism for classes:

```
class Window(props: WindowProps) {
    private var glfwWindow: CPointer<GLFWwindow>? = null

    private val propsStableRef = StableRef.create(props)  // <----- nice, but painfully because I can't write an auto cleanup for it for when the class instance dies

    @ThreadLocal
    private companion object {
        var isGLFWInitialized = false
    }

    init {
        if (!isGLFWInitialized) {
            val success = glfwInit()
            assertEquals(GLFW_TRUE, success, "Could not intialize GLFW!")

            isGLFWInitialized = true
        }

        glfwWindow = glfwCreateWindow(props.width, props.height, props.title, null, null)
        glfwMakeContextCurrent(glfwWindow)

        glfwSetWindowUserPointer(glfwWindow, propsStableRef.asCPointer())
    }

    // skipped for brevity
}
```

Now if there would be some kind of auto destruction method I would want to write something like this:
```
class Window(props: WindowProps) {
    // skipped for brevity

    init {
        // skipped for brevity
    }

    // this is something I would really like to have in Kotlin
    destruct {
        propsStableRef.dispose()
        glfwTerminate()
    }
}
```

Any sane alternative would be appreciated that's why I think this can be tagged as both a feature request and a question.

**Comment by arpie42** [comment]
I would also be very interested in an official response to this request/question.

**Comment by artdfel** [comment]
Hello, @DrOptix! The destructors absence is known to be a problem sometimes. There was an [issue](https://github.com/JetBrains/kotlin-native/issues/2327) some time ago, but your case brings a valuable opinion on it. As the old one was closed, let's leave this one open - such feature design should be discussed further.

**Comment by nlbuescher** [comment]
I also struggle with the lack of a `finalize` (JVM function for cleaning up before the GC clears the object) equivalent for the same reasons. From the old issue you mentioned:

> Deallocation of objects in systems with automated memory management can happen very late or (in theory) even never.

The fact that we are never sure when exactly memory will be deallocated seems to be the reason that the old issue was closed, but overall, I've been struggling with trying to wrap C structs in Kotlin classes without any sort of finalize equivalent simply because I don't care at what time the memory gets cleaned up, I only care that when it does, it also cleans up the other things it created (possibly on the heap). With a proper finalize, I can prevent memory leaks. due to having to manually manage memory when dealing with Cinterop types.

**Comment by DrOptix** [comment]
Any news about this? I know I can create a helper function similar to C# using and an IDestroyable interface to implement some kind of automatic cleanup, but still it is not enough. What about implementing something like this in Kotlin/Native?

Check InstrumentationTimer class:
https://github.com/TheCherno/Hazel/blob/master/Hazel/src/Hazel/Debug/Instrumentor.h#L144

I don't care about JVM. I may have some interest in JS, but my main focus is on native. I really want a nicer alternative to C++, Kotlin seems to be it, but without destructors and destructors called when the scope ends is really not nice.

**Comment by SvyatoslavScherbina** [comment]
Your use case is unclear to me. Could you please provide more details?
Your code example
```
    // this is something I would really like to have in Kotlin
    destruct {
        propsStableRef.dispose()
        glfwTerminate()
    }
```
doesn't destroy `glfwWindow`. Is this intentional? Which code does destroy it?

`destruct` block can only be called after the `Window` object gets garbage collected.
So if `glfwWindow` should be destroyed in this `destruct` block too, could this make your UI non-deterministic?

I guess one should destroy the resources of `Window` after the window gets closed, either by user or by internal logic. In any case, does anything prevent you from listening a close event and dispose the resources in the callback?

**Comment by DrOptix** [comment]
I no longer have the full example from the initial code snipper, but I will try to give a more clear example bellow, with something other than a Window because then yes you may get arround this limitation by listening to events.

I will try to port the C++ example I've linked above

```
package TaskForceTracer

import kotlin.system.getTimeMicros
import kotlin.system.measureNanoTime

class InstrumentationTimer(methodName: String) {
    private var _isStopped = false
    
    init {
        val _startTimepoint = getTimeMicros()
    }

    // destruct {
    //     val endTimepoint = getTimeMicros()
    //     val elapsedTime = endTimepoint - _startTimepoint

    //     // SOmehow log the elapsed time, maybe using chrome trace format
    //     println(elapsedTime)
    // }
}

// Usa case
fun foo() {
    // Nice would be to have something like C++ __FUNCSIG__ or __FUNC__
    // Instead of "foo"
    InstrumentationTimer("foo")
}

fun main() {
    foo()

    // I know I have this, but honestly it looks a bit bad if you ask me, and how to disable it in
    // a release build
    println("This is in nanosec, but the idea matters ${measureNanoTime(::foo)}")
}
```

I would like the `destruct` block to be called when the scope of `foo()` ends.

I hope this is clear now. If an instrumentation timer is yet a bad example I will try to come up with something else

**Comment by SvyatoslavScherbina** [comment]
So, for this particular case binding "destructor" to object deallocation is pretty useless, since Kotlin doesn't have a concept of deterministic object lifetime. The most applicable concept here would be a finalizer, and I guess you won't put  your `destruct` code on JVM into `finalize` that can be executed much later than the scope ends.
Destructors/finalizers/whatever for Kotlin objects won't help in your case.

It seems that actually you don't need destructors for objects. You probably need to rely on the end of scope, which is completely different thing.
The most straightforward way here is to define and use `inline` functions like `measureNanoTime`. Disabling anything in release build is possible the same way as with potential destructors.

If you _absolutely_ need RAII-style approach involving creating a new object, you can emulate it with  `memScoped` and its `.defer`. These are pure Kotlin concepts, you can implement an alternative by yourself.
```kotlin
import kotlinx.cinterop.MemScope
import kotlinx.cinterop.memScoped
import kotlin.system.getTimeMicros
import kotlin.system.measureNanoTime

class InstrumentationTimer(methodName: String) {
    private var _isStopped = false

    val _startTimepoint = getTimeMicros()

    fun dispose() {
        val endTimepoint = getTimeMicros()
        val elapsedTime = endTimepoint - _startTimepoint

        // SOmehow log the elapsed time, maybe using chrome trace format
        println(elapsedTime)
    }
}

fun MemScope.instrumentationTimer(methodName: String): InstrumentationTimer {
    val result = InstrumentationTimer(methodName)
    this.defer { result.dispose() }
    return result
}

// Usa case
fun foo() = memScoped {
    // Nice would be to have something like C++ __FUNCSIG__ or __FUNC__
    // Instead of "foo"
    instrumentationTimer("foo")
}

fun main() {
    foo()

    // I know I have this, but honestly it looks a bit bad if you ask me, and how to disable it in
    // a release build
    println("This is in nanosec, but the idea matters ${measureNanoTime(::foo)}")
}
```

In both cases, something like decorators might be useful to simplify the code. There are some ideas about decorators in Kotlin, see this talk for more details: https://youtu.be/0FF19HJDqMo?t=984

**Comment by arpie42** [comment]
> If you absolutely need RAII-style approach involving creating a new object, you can emulate it with memScoped and its .defer. These are pure Kotlin concepts, you can implement an alternative by yourself.

I'm probably being dumb but I've looked for the source for memScoped and/or .defer so that I can try to implement something similar myself, but I can't find it anywhere.  Any chance of a link to their source code please?

**Comment by SvyatoslavScherbina** [comment]
https://github.com/JetBrains/kotlin-native/blob/6f4864c875950bba8f578e62ece0a95eb3b9c33f/Interop/Runtime/src/main/kotlin/kotlinx/cinterop/Utils.kt#L630
https://github.com/JetBrains/kotlin-native/blob/6f4864c875950bba8f578e62ece0a95eb3b9c33f/Interop/Runtime/src/main/kotlin/kotlinx/cinterop/Utils.kt#L53
(`TODO` part might be obsolete, didn't check).
Generally interop and native memory allocation parts of this machinery are not relevant for `defer`.

**Comment by SvyatoslavScherbina** [comment]
Got no response explaining the actual use case, closing.
Feel free to submit properly explained feature requests to YouTrack: https://kotl.in/issue

**Comment by felixSchl** [comment]
Has there been any movement on this? What is the objection of adding this feature to Kotlin/Native? I think it makes perfect sense to expose this function in order to be able to automatically release cinterop related memory allocations. I understand and agree that finalizers are not suitable for general purpose resource clean up, however, as far as memory management is concerned I think they they are very much justified. Should further discussion happen here or over at https://youtrack.jetbrains.com/issue/KT-44191?

**Comment by SvyatoslavScherbina** [comment]
> What is the objection of adding this feature to Kotlin/Native?

Please read the comments above, and also in https://github.com/JetBrains/kotlin-native/issues/2327.

> I understand and agree that finalizers are not suitable for general purpose resource clean up, however, as far as memory management is concerned I think they are very much justified.

Is it possible to enable the latter but not the former?
 
> Should further discussion happen here or over at https://youtrack.jetbrains.com/issue/KT-44191?

Yes, please.
