### ISSUE TITLE
Important: please use YouTrack for bugs and feature requests

### ISSUE THREAD

**Issue by SvyatoslavScherbina** [JetBrains/kotlin-native#4079]
Hello.

We at Kotlin/Native team are going to migrate issue tracking from this repository to Kotlin issue tracker  - [YouTrack](https://youtrack.jetbrains.com/issues/KT). Please use it instead of GitHub when reporting bugs or requesting features in Kotlin/Native.

To create a new issue in YouTrack, follow the link: https://kotl.in/issue

Kotlin/Native is an inseparable part of Kotlin project. We believe that using the same issue tracker is critical to getting issues found and fixed.

If you have a question about Kotlin/Native, please ask it on StackOverflow with `kotlin-native` tag: https://stackoverflow.com/questions/ask?tags=kotlin-native.

If you encounter a problem but have no idea whether it is caused by a bug/missing feature or just lack of understanding, prefer using StackOverflow.

Also feel free to ask or discuss anything on `#kotlin-native` and `#multiplatform` channels in Slack workspace for Kotlin community -- https://slack.kotl.in.

Please avoid creating new issues in kotlin-native GitHub repo.

**Comment by LifeIsStrange** [comment]
Here's my opinion:
Yes indeed it's probably better for kotlin native to share the same infrastructure with kotlin jvm. 
*But*
I understand that youtrack is made by JetBrains and that jetbrains wants to promote it. I might even believe that youtrack has advantages over github (and conversely). 
But crucially, Kotlin would benefit a lot from external open source contributions. The Rust language for example has had an astonishing number of contributors (2000?). 
Yes in an ideal world external contributors could come contribute to a youtrack repository but culturally I believe it is a fact that people have much more chance to contribute if you are on github.com. 
This is how I work: if I want to contribute here's the chances that I actually contribute: github - > gitlab - > youtrack in that order.
In part because it's not enough smartphone friendly, in part because it's quite slow (I'm referring to the main loader) but the biggest part is because it's far less *familiar* than github and you cannot adress this last point. 
I believe to be representative of a lot of persons. 
This loss of potential contributors will do a lot of harm to Kotlin or at least a lot of missed growth. 

Here's what you should do:
1) in an ideal world: The youtrack developers add the feature to automatically synchronize, in real-time a youtrack repo with a github.com one so that any youtrack issue map à github one, any change is reflected in both sites. 
This would solve the issue AND would actually allow youtrack as a product to massively win marketshare. 
The overlap of features/semantic needs to be carefully analyzed/thought for enabling such a sync mode. 
2) If it was too hard to implement, or too long term of a change, I believe that you should migrate Kotlin (be it JVM, JS, native) to github.com in order to increase language growth and commitment to open source (while youtrack allow opensource repositories, it's culturally less open because of the intrinsic cultural, psychological but real barrier to entry)
As a reminder Kotlinx.coroutines and Kotlin io already are on github.com.

The loss of contributions and contributors should not be understated. With mostly only contributors, rust has achieved ~100000 commits!

**Comment by SvyatoslavScherbina** [comment]
@LifeIsStrange 
> I understand that youtrack is made by JetBrains and that jetbrains wants to promote it.

Using YouTrack for tracking Kotlin/Native issues has nothing to do with promoting YouTrack.

> I might even believe that youtrack has advantages over github (and conversely).

This is the real reason. I find YouTrack much more flexible that GitHub Issues.

> But crucially, Kotlin would benefit a lot from external open source contributions. The Rust language for example has had an astonishing number of contributors (2000?).
> Yes in an ideal world external contributors could come contribute to a youtrack repository but culturally I believe it is a fact that people have much more chance to contribute if you are on github.com. 

YouTrack is not a source management system, not a VCS. It doesn't provide a Git hosting. Kotlin sources are hosted on GitHub, we aren't migrating sources to YouTrack. You can contribute using a GitHub pull request.
This is also relevant to other statements and proposals in your comment. Please correct me if I wrong.

Also note that you can login to YouTrack using your GitHub account.

**Comment by koyakei** [comment]
@SvyatoslavScherbina I can not find kotlin native tag.
Can you create and tag old issue in YouTrack?
https://youtrack.jetbrains.com/issues/JT
![image](https://user-images.githubusercontent.com/4229382/90998069-29905480-e5fe-11ea-9a6d-92d3052c2798.png)

**Comment by artdfel** [comment]
Hello, @koyakei! There is no specific tag available from the reporter side. If there is a need to emphasize the issue is about Kotlin/Native, one can just put [Kotlin/Native] at the beginning of the report title. To reveal issues that were already reported, please use `Subsystems:` field in the search queue.

**Comment by koyakei** [comment]
@artdfel thank you very much Itry it

**Comment by SvyatoslavScherbina** [comment]
@koyakei also note that https://youtrack.jetbrains.com hosts issues for a lot of JetBrains projects.
According to your screenshot, you are looking for Kotlin/Native issues in "YouTrack" project, which contains issues with the YouTrack itself. "Kotlin" project would probably be more useful: https://youtrack.jetbrains.com/issues/KT

**Comment by koyakei** [comment]
@SvyatoslavScherbina thank you. But kotlin native is big project. So I think KT/NT tag should be build
