### ISSUE TITLE
Why publishLibraryVariants don't work ?

### ISSUE THREAD

**Issue by VincentChen1212** [JetBrains/kotlin-native#4400]
My build.gradle.kts
```
plugins {
    id("com.android.library")
    kotlin("multiplatform") version "1.4.10"
}
......
kotlin {
    targets {
    .....
        android {
            publishLibraryVariants("release")
        }
    }
}
```

but still generate debug.aar and release.aar in the outputs folder.

and
if
```
plugins {
    kotlin("multiplatform") version "1.4.10"
    id("com.android.library")
}
```
will get error (not find release buildtype...??)

is anything wrong with my setting?

thank you.

**Comment by artdfel** [comment]
Hello, @VincentChen1212! As you probably noticed, Kotlin/Native issue tracker is migrating(see #4079), so we sincerely ask to avoid reporting to this one. 
However, this particular question seems to be unrelated, as your problem is caused by the Kotlin Multiplatform Gradle plugin interfering with the Android plugin for Gradle or vice versa. Please consider reporting it on the YouTrack, and extend the report with a stable project reproducing the problem.
