### ISSUE TITLE
Does kotlin native support windows platform?

### ISSUE THREAD

**Issue by netroby** [JetBrains/kotlin-native#461]
Does kotlin native support windows platform?
How to play kotlin native on windows platform? Any document guide us?

**Comment by olonho** [comment]
No, neither Windows hosts nor targets are not supported at the moment. This may be reconsidered in the future, but no concrete plans yet.

**Comment by Scellow** [comment]
+1 for Windows, if making game, then Windows is important

**Comment by Restioson** [comment]
+1

**Comment by netroby** [comment]
Golang, rust support windows, so they grows well.

**Comment by sgf** [comment]
@netroby @olonho @Restioson @Scellow 
Supporting Windows is a very important strategy. After all, Windows has a very large user capacity. And because C # (. NET native) is not going well(seems will always support UWP only). 
The Llic project(https://github.com/dotnet/llilc) seems to have been abandoned.

Kotlin should quickly preempt the market.If so, Kotlin is maybe  can be to replace the position of C++.
Become a mainstream native language.

sorry,my bad english.

**Comment by Restioson** [comment]
I don't think a language needs to preempt anything, or force people to use it just because it's popular. The goal should be to create a clear, beautiful, and functioning (not function*al* ) language.

**Comment by sgf** [comment]
@Restioson Kotlin is not better than java in JVM?
i think there is many Beautiful Language is died in history.
C++ is not good and Beautiful,but why its soo popular?
Do Supports a platform is not force any one,just Give people more choices..

**Comment by Restioson** [comment]
> Kotlin should quickly preempt the market.If so, Kotlin is maybe can to replace the position of C++

This, to me, sounds a bit hostile. You don't need to "preempt" anything. Replacing C++ would mean forcing people to use it over C++ as I see it.

**Comment by Restioson** [comment]
I do agree that it should be compilable to native Windows executables, if possible.

**Comment by pvcresin** [comment]
https://blog.jetbrains.com/kotlin/2017/06/kotlinnative-v0-3-is-out/

> With the release of version v0.3 Windows is supported as both a compilation host and execution target, and Google Android devices as an execution target with native activities.

awesome!

**Comment by Plast0000** [comment]
Until Windows support is ready, enable WSL on Windows 10 and install ubuntu bash and run kotlin apps from there. or just make a vm.
I really hope Windows support drops in soon

**Comment by dazza5000** [comment]
I am new to this. Does anyone know if we can target Windows XP with kotlin native?

**Comment by harry1453** [comment]
@dazza5000 In my experience you cannot target Windows XP, even when using the `mingwX86` target because Kotlin/Native runtime imports [GetTickCount64](https://docs.microsoft.com/en-us/windows/win32/api/sysinfoapi/nf-sysinfoapi-gettickcount64), which, according to the documentation, is only available in Kernel32.dll on Windows Vista / Server 2008 or newer. If you try to run a Kotlin/Native program on Windows XP you get an error message saying that GetTickCount64 could not be found.

**Comment by dazza5000** [comment]
thank you @harry1453 - a very thorough response!
