### ISSUE TITLE
Include name of program in main

### ISSUE THREAD

**Issue by AdrianVovk** [JetBrains/kotlin-native#555]
The first object of `argv` is left out. This is a problem because it is nice to have a way to get the name of the file being executed.

### Example
```kotlin
fun main(execname: String, args: Array<String>) {
   if (!checkargs(args)) {
      println("Usage: $execname [OPTIONS] - Test program")
      println("   --help: Display help message")
      println("   --somearg: This does something")
      println("   --version: Print out the version")
      exit(1)
   }

   // Program
}
```
Compiled as `Program.kexe`
```
user@hostname:~/dir/$ ./Program.kexe --badvar
Usage: Program.kexe [OPTIONS] - Test Program
   --help: Display help message
   --somearg: This does something
   --version: Print out the version
```
Then renamed to `program`
```
user@hostname:~/dir/$ ./program --badvar
Usage: program [OPTIONS] - Test Program
   --help: Display help message
   --somearg: This does something
   --version: Print out the version
```

**Comment by olonho** [comment]
Yes, this is known and discussed implementation detail. It came from Kotlin/JVM and Kotlin/JS compatibility, where executable name isn't available.  Instead of changing argv list or adding additional main() parameter, plan is to add API to standard library which provides access to this information. Also note that for some scenarios this API is somewhat non-trivial to implement.

**Comment by iBelieve** [comment]
@olonho But isn't C compatibility more of a concern than JVM/JS compatibility? For example, g_application_run expects an array of command line args, including the program name.

**Comment by olonho** [comment]
Currently we decided not to support this feature.
