### ISSUE TITLE
How to Generate IR (.ll) files?

### ISSUE THREAD

**Issue by aydin192** [JetBrains/kotlin-native#692]
Hi,

Is there any way we can generate IR files (a .ll file) like the way we do it with `clang` and its `emit-llvm` option? For example I can generate an IR file, _test.ll_, from my _test.c_ using following command:

`clang -S -emit-llvm test.c`

Regards,
Aydin

**Comment by r4zzz4k** [comment]
I don't think it's essential for `konanc` to be able to emit both `.ll` and `.bc`, because you can use `llvm-dis` and `llvm-as` to convert between them. If I understand correctly (I don't have much of an experience with LLVM), they are interchangable -- `.ll` is text form (assembly) and `.bc` is binary form (bitcode).
Most of LLVM utilities such as `llc` can consume both formats as an input, so you don't even need to disassemble bitcode files.

**Comment by vvlevchenko** [comment]
not an issue.
